sidebar_background_color:
  type: string
  default: white
  description: "Side-bar background color"
  
header_font_color:
  type: string
  default: black
  description: "Section headers font color"

header_font_weight:
  type: enum
  default: normal
  choices:
    - normal
    - bold
  description: "Section headers font weight"

header_font_size:
  type: integer
  default: 15
  description: "Section headers text size"
  
link_font_color:
  type: string
  default: black
  description: "Section link font color"

link_font_size:
  type: integer
  default: 15
  description: "Section links text size"

hide_community_section:
  type: bool
  default: false
  description: "Hide the Community Section"
  
hide_anniversaries:
  type: bool
  default: false
  description: "Hide the Anniversaries link in the More section"
  
hide_birthdays:
  type: bool
  default: false
  description: "Hide the Birthdays link in the More section"
  
hide_categories_section:
  type: bool
  default: false
  description: "Hide the Categories Section"
  
hide_tags_section:
  type: bool
  default: false
  description: "Hide the Tags Section"

hide_messages_section:
  type: bool
  default: false
  description: "Hide the Messages Section"

hide_channels_section:
  type: bool
  default: false
  description: "Hide the Channels Section"

hide_personal_chat_section:
  type: bool
  default: false
  description: "Hide the Personal Chat Section"

hide_category_bullets:
  type: bool
  default: false
  description: "Hide the Category bullets"
  
category_bullet_rounding:
  type: enum
  default: 0
  choices:
    - 0
    - 10%
    - 20%
    - 30%
    - 40%
    - 50%
  description: "Category bullet rounding"
  
category_bullet_size:
  type: enum
  default: auto
  choices:
    - auto
    - 0.7em
    - 0.8em
    - 0.9em
    - 1.0em
   description: "Category bullet size in ems. Default is 1.0" 
  
hide_lock_icon:
  type: bool
  default: false
  description: "Hide the lock badge icon for secured categories"
  
