sidebar_background_color:
  type: string
  default: ""
  description: "Side-bar background color."
  
more_section_background_color:
  type: enum
  default: ""
  choices:
    - aliceblue
    - antiquewhite
    - aqua
    - aquamarine
    - azure
    - beige
    - bisque
    - black
    - blanchedalmond
    - blue
    - blueviolet
    - brown
    - burlywood
    - cadetblue
    - chartreuse
    - chocolate
    - coral
    - cornflowerblue
    - cornsilk
    - crimson
    - cyan
    - darkblue
    - darkcyan
    - darkgoldenrod
    - darkgray
    - darkgreen
    - darkgrey
    - darkkhaki
    - darkmagenta
    - darkolivegreen
    - darkorange
    - darkorchid
    - darkred
    - darksalmon
    - darkseagreen
    - darkslateblue
    - darkslategray
    - darkslategrey
    - darkturquoise
    - darkviolet
    - deeppink
    - deepskyblue
    - dimgray
    - dimgrey
    - dodgerblue
    - firebrick
    - floralwhite
    - forestgreen
    - fuchsia
    - gainsboro
    - ghostwhite
    - gold
    - goldenrod
    - gray
    - green
    - greenyellow
    - grey
    - honeydew
    - hotpink
    - indianred
    - indigo
    - ivory
    - khaki
    - lavender
    - lavenderblush
    - lawngreen
    - lemonchiffon
    - lightblue
    - lightcoral
    - lightcyan
    - lightgoldenrodyellow
    - lightgray
    - lightgreen
    - lightgrey
    - lightpink
    - lightsalmon
    - lightseagreen
    - lightskyblue
    - lightslategray
    - lightslategrey
    - lightsteelblue
    - lightyellow
    - lime
    - limegreen
    - linen
    - magenta
    - maroon
    - mediumaquamarine
    - mediumblue
    - mediumorchid
    - mediumpurple
    - mediumseagreen
    - mediumslateblue
    - mediumspringgreen
    - mediumturquoise
    - mediumvioletred
    - midnightblue
    - mintcream
    - mistyrose
    - moccasin
    - navajowhite
    - navy
    - oldlace
    - olive
    - olivedrab
    - orange
    - orangered
    - orchid
    - palegoldenrod
    - palegreen
    - paleturquoise
    - palevioletred
    - papayawhip
    - peachpuff
    - peru
    - pink
    - plum
    - powderblue
    - purple
    - red
    - rosybrown
    - royalblue
    - saddlebrown
    - salmon
    - sandybrown
    - seagreen
    - seashell
    - sienna
    - silver
    - skyblue
    - slateblue
    - slategray
    - slategrey
    - snow
    - springgreen
    - steelblue
    - tan
    - teal
    - thistle
    - tomato
    - turquoise
    - violet
    - wheat
    - white
    - whitesmoke
    - yellow
    - yellowgreen
  description: "More section background color."

header_font_color:
  type: string
  default: ""
  description: "Section headers font color. Leave blank for default."

header_font_weight:
  type: enum
  default: normal
  choices:
    - normal
    - bold
  description: "Section headers font weight"

header_font_size:
  type: enum
  default: ""
  choices:
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
  description: "Section headers text size in px. Leave blank for default."
  
link_font_color:
  type: string
  default: ""
  description: "Section link font color Leave blank for default."

link_font_size:
  type: enum
  default: ""
  choices:
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
  description: "Section links text size in px. Leave blank for default."
  
current_link_font_color:
  type: string
  default: ""
  description: "Current link font color. Leave blank for default."
  
current_link_background_color:
  type: string
  default: ""
  description: "Background color of the current link. Leave blank for default."
 
current_link_icon_color:
  type: enum
  default: ""
  choices:
    - maroon
    - red
    - pink
    - fuchsia
    - purple
    - blue
    - navy
    - teal
    - lime
    - green
    - aqua
    - olive
    - gold   
    - yellow
    - silver
    - grey
    - white
    - black
  description: "Color of the current link icon. Leave blank for default."
  
hide_community_section:
  type: bool
  default: false
  description: "Hide the Community Section"
  
hide_community_section_from_anon:
  type: bool
  default: false
  description: "Hide the Community Section from anonymous users only."
    
hide_anniversaries:
  type: bool
  default: false
  description: "Hide the Anniversaries link in the More section."

hide_birthdays:
  type: bool
  default: false
  description: "Hide the Birthdays link in the More section."
  
hide_categories_section:
  type: bool
  default: false
  description: "Hide the Categories Section."
  
hide_categories_from_anon:
  type: bool
  default: false
  description: "Hide the Categories Section from anonymous users only."

hide_tags_section:
  type: bool
  default: false
  description: "Hide the Tags Section."
  
hide_tags_from_anon:
  type: bool
  default: false
  description: "Hide the Tags Section from anonymous users only."

hide_messages_section:
  type: bool
  default: false
  description: "Hide the Messages Section."

hide_channels_section:
  type: bool
  default: false
  description: "Hide the Channels Section."

hide_personal_chat_section:
  type: bool
  default: false
  description: "Hide the Personal Chat Section."

hide_category_bullets:
  type: bool
  default: false
  description: "Hide the Category bullets in the side-bar."
  
hide_lock_icon:
  type: bool
  default: false
  description: "Hide the lock badge icon for secured categories in the side-bar."

category_bullet_rounding:
  type: enum
  default: 0
  choices:
    - 0
    - 10%
    - 20%
    - 30%
    - 40%
    - 50%
  description: "Category bullet rounding. 0 = square, 50% = circle."
