sidebar_background_color:
  type: string
  default: white
  
header_font_color:
  type: string
  default: black
  
header_font_weight:
  type: string
  default: normal
  
header_font_size:
  type: integer
  default: 15

hide_sidebar-community:
  default: false
