sidebar_background_color:
  type: string
  default: gray

transp:
  type: float
  default: 0.80
  
header_font_color:
  type: string
  default: black
  
header_font_weight:
  type: string
  default: normal
  
header_font_size:
  type: integer
  default: 15
