header_font_color:
  type: string
  default: ""
  description: "Section headers font color. Leave blank for default."

header_font_weight:
  type: enum
  default: normal
  choices:
    - normal
    - bold
  description: "Section headers font weight"

header_font_size:
  type: enum
  default: ""
  choices:
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
  description: "Section headers text size in px. Leave blank for default."
  
link_font_color:
  type: string
  default: ""
  description: "Section link font color Leave blank for default."

link_font_size:
  type: enum
  default: ""
  choices:
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
  description: "Section links text size in px. Leave blank for default."
  
active_link_font_color:
  type: string
  default: ""
  description: "Current link font color. Leave blank for default."

hide_community_section:
  type: bool
  default: false
  description: "Hide the Community Section"
  
hide_community_section_from_anon:
  type: bool
  default: false
  description: "Hide the Community Section from anonymous users only."
    
hide_anniversaries:
  type: bool
  default: false
  description: "Hide the Anniversaries link in the More section."
    
hide_anniversaries_from_anon:
  type: bool
  default: false
  description: "Hide the Anniversaries link in the More section from anonymous users only."
  
hide_birthdays:
  type: bool
  default: false
  description: "Hide the Birthdays link in the More section."
  
hide_birthdays_from_anon:
  type: bool
  default: false
  description: "Hide the Birthdays link in the More section from anonymous users only."
  
hide_categories_section:
  type: bool
  default: false
  description: "Hide the Categories Section."
  
hide_categories_from_anon:
  type: bool
  default: false
  description: "Hide the Categories Section from anonymous users only."

hide_tags_section:
  type: bool
  default: false
  description: "Hide the Tags Section."
  
hide_tags_from_anon:
  type: bool
  default: false
  description: "Hide the Tags Section from anonymous users only."

hide_messages_section:
  type: bool
  default: false
  description: "Hide the Messages Section."

hide_channels_section:
  type: bool
  default: false
  description: "Hide the Channels Section."

hide_personal_chat_section:
  type: bool
  default: false
  description: "Hide the Personal Chat Section."

hide_category_bullets:
  type: bool
  default: false
  description: "Hide the Category bullets in the side-bar."
  
hide_lock_icon:
  type: bool
  default: false
  description: "Hide the lock badge icon for secured categories in the side-bar."

category_bullet_rounding:
  type: enum
  default: 0
  choices:
    - 0
    - 10%
    - 20%
    - 30%
    - 40%
    - 50%
  description: "Category bullet rounding. 0 = square, 50% = circle."
  
current_link_icon_color:
  type: enum
  default: ""
  choices:
    - red
    - pink
    - purple
    - blue
    - navy
    - green
    - aqua
    - gold   
    - yellow
    - silver
    - slategrey
    - white
    - black
  description: "Color of the current link icon. Leave blank for default."
